### ISSUE TITLE
A more general question on the builder

### ISSUE THREAD

**Issue by hugofloresgarcia** [shakfu/py-js#12]
hi @shakfu!

Came here from our conversation in [unloop](https://github.com/hugofloresgarcia/unloop/issues/2), which I unfortunately have had to slow down on due to other work I've had to do for grad school. 

I wanted to ask about your relocatable python builder (I think it's referred to as `relocatable-python` by the makefile entrypoint). More specifically, I'd like to be able to build a portable python distribution that I can embed into a VST3 plugin so I can call the `gradio-client` from the plugin (similar to what I wanted to do with unloop). My VST3 is built using JUCE, using CMake to take care of the build process? 

I was wondering if you could point me in the right direction to see if it's possible to embed python in a C++ app w/ a Cmake build system using your builder? 

Thanks in advance!

**Comment by shakfu** [comment]
Hi @hugofloresgarcia 

Interesting question. I have never hear of embedding python into a VST... 

Incidentally, the py-js relocatable python build variant using the `relocatable-python` makefile target is based on Greg Neagle's project with the same name. I have also included some other projects which may be useful to your task:

- [relocatable-python](https://github.com/gregneagle/relocatable-python): A tool for building standalone relocatable Python.framework bundles.

- [python-cmake-buildsystem](https://github.com/python-cmake-buildsystem/python-cmake-buildsystem): A cmake buildsystem for compiling Python. Probably what you are looking for.

- [python-build-standalone](https://github.com/indygreg/python-build-standalone): Produce redistributable builds of Python.

- [Python Apple Support](https://github.com/beeware/Python-Apple-support): A meta-package for building a version of Python that can be embedded into a macOS, iOS, tvOS or watchOS project.

**Comment by hugofloresgarcia** [comment]
Ended up going with relocatable-python, and everything worked! Thanks so much @shakfu!

**Comment by shakfu** [comment]
My pleasure. Glad it worked out for you @hugofloresgarcia
