### ISSUE TITLE
feature request | buffer~ support

### ISSUE THREAD

**Issue by jamesb93** [shakfu/py-js#13]
Hi,

This is quite literally insane work and very good. I've been trying it out and it's really nice having the ability to sign atoms as well as define handlers, much like js.

To me this is basically a Python object done right :)

One thing that for me would be especially useful for machine learning skullduggery would be a buffer~ interface to both read/write buffer data from Python. How feasible is something like this? Can I help in any way? Certainly not a C++ expert but if you point me in the right places I can certainly have a crack.

**Comment by shakfu** [comment]
Hi @jamesb93 

> This is quite literally insane work and very good. I've been trying it out and it's really nice having the ability to sign atoms as well as define handlers, much like js.
>
> To me this is basically a Python object done right :)

Thanks for your enthusiastic interest in `py-js` :smile: 

> One thing that for me would be especially useful for machine learning skullduggery would be a buffer~ interface to both read/write buffer data from Python. How feasible is something like this? Can I help in any way? Certainly not a C++ expert but if you point me in the right places I can certainly have a crack. 

This would be a nice feature for sure. I had a look at the `buffer~` api in the Max-sdkdocs (
Max-API page 556 section 38.36) and it has the following c-api:




```c

// ------------------------------------------------------------------------
// buffer~ structs

struct t_buffer_info;

// ------------------------------------------------------------------------
// buffer~ typedefs

// A buffer~ reference
typedef struct _buffer_ref t_buffer_ref;

// A buffer∼ object.
typedef t_object t_buffer_obj;

// ------------------------------------------------------------------------
// buffer~ functions

// refs

// Create a reference to a buffer∼ object by name.
BEGIN_USING_C_LINKAGE t_buffer_ref ∗ buffer_ref_new (t_object ∗self, t_symbol ∗name);

// Change a buffer reference to refer to a different buffer∼ object by name.
void buffer_ref_set (t_buffer_ref ∗x, t_symbol ∗name);

// Query to find out if a buffer∼ with the referenced name actually exists.
t_atom_long buffer_ref_exists (t_buffer_ref ∗x);

// Query a buffer reference to get the actual buffer∼ object being referenced, if it exists.
t_buffer_obj ∗ buffer_ref_getobject (t_buffer_ref ∗x);

// Your object needs to handle notifications issued by the buffer∼ you reference.
t_max_err buffer_ref_notify (t_buffer_ref ∗x, t_symbol ∗s, t_symbol ∗msg, void ∗sender, void ∗data);

// objects

// Open a viewer window to display the contents of the buffer∼.
void buffer_view (t_buffer_obj ∗buffer_object);

// Claim the buffer∼ and get a pointer to the first sample in memory.
float ∗ buffer_locksamples (t_buffer_obj ∗buffer_object);

// Release your claim on the buffer∼ contents so that other objects may read/write to the buffer∼.
void buffer_unlocksamples (t_buffer_obj ∗buffer_object);

// Query a buffer∼ to find out how many channels are present in the buffer content.
t_atom_long buffer_getchannelcount (t_buffer_obj ∗buffer_object);

// Query a buffer∼ to find out how many frames long the buffer content is in samples.
t_atom_long buffer_getframecount (t_buffer_obj ∗buffer_object);

// Query a buffer∼ to find out its native sample rate in samples per second.
t_atom_float buffer_getsamplerate (t_buffer_obj ∗buffer_object);

// Query a buffer∼ to find out its native sample rate in samples per millisecond.
t_atom_float buffer_getmillisamplerate (t_buffer_obj ∗buffer_object);

// Set the number of samples with which to zero-pad the buffer∼'s contents.
t_max_err buffer_setpadding (t_buffer_obj ∗buffer_object, t_atom_long samplecount);

// Set the buffer's dirty flag, indicating that changes have been made.
t_max_err buffer_setdirty (t_buffer_obj ∗buffer_object);

// Retrieve the name of the last file to be read by a buffer∼.
t_symbol ∗ buffer_getfilename (t_buffer_obj ∗buffer_object);
```

The most likely approach would be to implement a cython wrapper in the `api.pyx` file and then enable a way to exchange data with numpy. The `api` module is exposed to the `py` object so this would be accessible from the Max side.

Let's see what can be done... if time permits, and of course, contributions would be welcome.

**Comment by shakfu** [comment]
It seems I forgot that I had already partially implemented the above buffer cython object (except for the numpy integration).

Have a look at the the Buffer class and tests in the `py-js/source/projects/py/api.pyx` file:

```cython
cdef class Buffer:
    """A wrapper class for a Max t_buffer_obj
    """
    cdef mp.t_buffer_obj *obj
    cdef mp.t_buffer_ref *ref
    # cdef mx.t_object *tobj # t_object with ref to buffer
    cdef bint is_locked
    cdef float* samples

    def __cinit__(self):
        self.obj = NULL
        self.ref = NULL
        self.samples = NULL
        self.is_locked = False

    def __dealloc__(self):
        # De-allocate if not null
        if self.ref is not NULL:
            mx.object_free(self.ref)
            self.ref = NULL

    @staticmethod
    cdef Buffer from_name(mx.t_object *x, str name):
        """Create a reference to a buffer~ object by name."""
        # Call to __new__ bypasses __init__ constructor
        cdef Buffer buffer = Buffer.__new__(Buffer)
        buffer.ref = mp.buffer_ref_new(x, str_to_sym(name))
        assert(mp.buffer_ref_exists(buffer.ref))
        buffer.obj = mp.buffer_ref_getobject(buffer.ref)
        return buffer

    def change_reference(self, str name):
        """Change a buffer reference to refer to a different buffer object by name."""
        mp.buffer_ref_set(self.ref, str_to_sym(name))
        assert(mp.buffer_ref_exists(self.ref))
        self.obj = mp.buffer_ref_getobject(self.ref)

    def view(self):
        """Open a viewer window to display the contents of the buffer."""
        mp.buffer_view(self.obj)

    @property
    def channelcount(self):
        """Get how many channels are present in the buffer content."""
        return mp.buffer_getchannelcount(self.obj)

    @property
    def framecount(self):
        """Get how many frames long the buffer content is in samples."""
        return mp.buffer_getframecount(self.obj)

    @property
    def samplerate(self):
        """Get the buffer's native sample rate in samples per second."""
        return mp.buffer_getsamplerate(self.obj)

    @property
    def millisamplerate(self):
        """Get the buffer's native sample rate in samples per millisecond."""
        return mp.buffer_getmillisamplerate(self.obj)

    @property
    def filename(self):
        """Retrieve the name of the last file to be read by a buffer~."""
        return sym_to_str(mp.buffer_getfilename(self.obj))

    def setdirty(self):
        """Set the buffer's dirty flag, indicating that changes have been made."""
        mp.buffer_setdirty(self.obj)

    def setpadding(self, long samplecount):
        """Set the number of samples with which to zero-pad the buffer~'s contents."""
        mp.buffer_setpadding(self.obj, samplecount)

    def locksamples(self):
        """Claim the buffer∼ and get a pointer to the first sample in memory."""
        self.samples = mp.buffer_locksamples(self.obj)
        self.is_locked = True

    def unlocksamples(self):
        """Release claim on buffer's contents so other objects can read/write to it."""
        mp.buffer_unlocksamples(self.obj)
        self.is_locked = False
```

It looks it requires some methods to allow set/get samples (floats) and then probably numpy integration would be nice.

Does this sound like what you need?

**Comment by jamesb93** [comment]
That sounds like what I would need to get going! I just had a cursory play by importing the `api` module into the python interpreter and seeing what I could do.

I tried creating a basic script to get the dimensions of a buffer:

```
import api

x = api.Buffer('x')
f = x.framecount

api.post(str(f))
```

This buffer 'x' exists in Max however the `framecount` property is always 0.

Perhaps my usage is incorrect though?

```
<pre><code>
----------begin_max5_patcher----------
499.3ocqT0zabBCD8L7qvxmoKeFzt8bNjK8X6kpnUFvv5Ur1H+wVPQo+1qYL
rYSYSJJoW.MOFOu4MuA+juGtPzSUXzWQ+D448jumG.MB3ME6gOQ5KaIJHM7I
pRQZn3.22zzdMfS6ok0rVJJ76JpTEdrXHTSU5QrMcCy42QzkGX7l8RZo1wax
t61DEfRxiGeEmGAQIahPONcHt4Di2R0PGj7BnvnmQimPYUP2HJN9kjYNcooG
5nNBwXziie4Ye+wGAqT4b5urkctnmIRN4DTQrIIaWTTbx1sKFKqQ4oQfjy9G
BO9lBOcoviyeakGfvEDdyk2WnZzmfJD9CQqw5xgeiTx3Zg5.5g6eeSkXzhVA
A5fnILE4LsZuscrpcOQqkrBi1sp4cY.eyi5gqnEllWg7I5N6jePePvsy+CPI
v.LX9etUfKlbgotlJ+MpGcTvaZG1PX0uism5VwSS2AK7Q28Q78jk99t2z1qs
iX8Ud9+Oo2IstvJVwcZMM4iH0nkRMCekDfZgaY7+9lLneFwestTBirbdzL+C
C5kVpxtCw3DMSvuJoLWN2bzsVhRVAOyMyBAR55NaWymxF3vZQGExwvsAPHi6
BygPI8LaNeXHhIRqAostiQ59epOOC6NpnhJ4FFXC9ipyRIX+iWyo5HNg.aI9
O6+GUwZfeB
-----------end_max5_patcher-----------
</code></pre>
```

**Comment by shakfu** [comment]
@jamesb93 

I understand the confusion: the cython api takes a little time to get used to, the best way to understand it is to look at the `api.pyx` file and its tests.

Still, there should have been a clearer way for users to get a buffer. That's my bad.

In any case, I have just pushed a commit to simplify getting an active buffer and also updated the `py.maxhelp` file to reflect this. The additional method is on the `PyExternal` class:

```python
    def get_buffer(self, str name):
        buf = Buffer.from_name(<mx.t_object*>self.obj, name)
        return buf
```

To explain this further: in my current implementation of the cython `api` module which wraps part of the Max c-api, the `PyExternal` object is a kind of virtual proxy to the `py` object that is instantiated at the Max level and gets a reference at creation:

```python
cdef class PyExternal:
    """Wraps the `py` external object and its methods.
    """
    cdef px.t_py *obj
    cdef bytes name

    def __cinit__(self):
        """Retrieves the py object name and reference.

        PY_OBJ_NAME is set to __builtins__ at object creation
        making it available to all modules.

        Since all py objects are registered, knowing the name
        allows any module in the namespace to get a reference
        (as below) to its parent object.
        """
        PY_OBJ_NAME = getattr(__builtins__, 'PY_OBJ_NAME')
        self.name = PY_OBJ_NAME.encode('utf-8')
        self.obj = <px.t_py *>mx.object_findregistered(
            mx.CLASS_BOX, mx.gensym(self.name))

    cpdef bang(self):
        px.py_bang(self.obj)

    # ...
```

So basically you need to first instantiate `PyExternal` to connect to the existing `py` external and then call `get_buffer` to get a buffer object.

So, to provide a concrete example (just tested), just `git pull` and `make projects` to recompile and then open `py.maxhelp`:

There will be a a `buffer~` object called `drum` that is loaded on opening `py.maxhelp` with `drumLoop.aif`. 

Enter the following in the code-editor (double click the py external to open the editor) it will run automatically on closing the window:

```python
import api

ext = api.PyExternal() # this step is necessary to get a reference to the `py` external instance
b = ext.get_buffer("drum") # b is a buffer instance
# test it
api.post(str(b.framecount))
b.view()
```

This should post the framecount to the console and also open a small window with.a shape of the samples loaded into the buffers (same as double-clicking the buffer object).

Hope this helps...

**Comment by shakfu** [comment]
Since there was a bug in my prior message I have updated it with a correction and provided an actual example in my last commit.

**Comment by shakfu** [comment]
@jamesb93 additional buffer support has been provided including buffer creation and retrieval by name. Check out `py.maxhelp` and `examples/scripts/test_buffer.py` for demo / examples.

**Comment by jamesb93** [comment]
Sorry for the silence, I'm currently moving houses 😅

This is great. I'll test it when I get a mo'.

**Comment by shakfu** [comment]
@jamesb93

Sure no problem. Incidentally committed some code to enable setting and getting samples from a buffer via numpy. There's a test to demonstrate this: `patchers/tests/test_buffer.maxpat` and also have a look at the pure python code in `examples/scripts/test_buffer.py` along the lines of the following:

```python
import api

import numpy as np
from scipy import signal

def test_buffer():
    # this step is necessary to get a reference to the `py` external instance
    ext = api.PyExternal()
    b = ext.get_buffer("drum") # b is a buffer instance

    # test it
    api.post(f"framecount: {b.framecount})")
    api.send("drum_scope", "set", "drum")
    b.view()


def test_create_buffer():
    name = "drum1"
    sample_file = "jongly.aif"
    buf = api.create_buffer(name, sample_file)
    api.post(f"created buffer name: '{name}' sample_file: '{sample_file}'")


def test_create_empty_buffer():
    name = "drum"
    duration_ms = 500
    buf = api.create_empty_buffer(name, duration_ms)
    api.post(f"created buffer name: '{name}' duration(ms): '{duration_ms}'")
    api.post(f"framecount: {buf.framecount}")


def test_get_buffer():
    buf = api.get_buffer("drum1")
    api.post(f"framecount: {buf.framecount}")
    api.send("drum_scope1", "set", "drum1")
    buf.view()
    return buf.samplerate 


def test_buffer_get_samples():
    name = "drum1"
    sample_file = "jongly.aif"
    buf = api.create_buffer(name, sample_file)
    api.post(f"created buffer name: '{name}' sample_file: '{sample_file}'")
    n_samples = buf.n_samples
    xs = np.array(buf.get_samples())
    assert len(xs) == n_samples
    api.post(f"get {n_samples} samples from buffer {name}")


def test_buffer_set_samples():
    name = "drum1"
    duration_ms = 500
    buf = api.create_empty_buffer(name, duration_ms)
    api.post("buffer.set_sample example with numpy and scipy.signal")
    api.post(f"created buffer name: '{name}' duration(ms): '{duration_ms}'")
    api.post(f"framecount: {buf.framecount}")
    n_samples = buf.n_samples
    t = np.linspace(0, 1, n_samples, endpoint=False, dtype=np.float64)
    xs = signal.sawtooth(2 * np.pi * 5 * t)
    buf.set_samples(xs)
    api.post(f"set {n_samples} samples to buffer {name}")
```

**Comment by jamesb93** [comment]
This is so great. Need to try it in more detail but in the abstract the API looks very sensible.

**Comment by shakfu** [comment]
Hi @jamesb93 

Thanks, incidentally there are some concrete demos of the buffer loading in `py.maxhelp` now as well. I've dedicate a folder for python tests which can be loaded via `[load <name>]` in `examples/tests`. You can find there buffer and api-level tests for a new `api.Patcher` object to facilitate patcher-related scripting.

**Comment by shakfu** [comment]
I've just added an example in `patchers/tests/test_buffer_array` which uses the builtin python array module in place of numpy to get and set data from a buffer.

This works great due the fantastic cython feature of [Typed Memoryviews](https://cython.readthedocs.io/en/latest/src/userguide/memoryviews.html)

**Comment by jamesb93** [comment]
Experimenting with some rudimentary things, I've found a relatively difficult thing to navigate. It is hard to pin the problem down, because the only thing that is reported to me is that some assertion went off.

Here is my script:

```py
import api
import librosa
import numpy as np
import pyloudnorm as pyln

def integrated_loudness(buffer_name):
    buf = api.get_buffer(buffer_name)
    sr = buf.samplerate
    l = (buf.n_samples / sr) * 1000
    meter = pyln.Meter(sr)
    audio_data = np.array(buf.get_samples())
    loudness = meter.integrated_loudness(audio_data)
    return 'loudness', loudness

def ebur(buffer_name):
    buf = api.get_buffer(buffer_name)
    sr = buf.samplerate
    l = (buf.n_samples / sr) * 1000
    meter = pyln.Meter(sr)
    audio_data = np.array(buf.get_samples())
    loudness = meter.integrated_loudness(audio_data)
    loudness_normalized_audio = pyln.normalize.loudness(audio_data, loudness, -12.0)
    outsize = (loudness_normalized_audio.shape[0] / sr) * 1000
    out = api.create_empty_buffer("goo", outsize)
    out.set_samples(loudness_normalized_audio)
```

The `integrated_loudness` function works. Really great! The `ebur` function however always asserts. I think its because when I call `set_samples` the size of `"goo"` is actually not the same as `loudness_normalized_audio`. 

What would be nice if there was a function like `set_samples` which also resized the buffer implicitly. This would greatly reduce the necessary steps to writing data back to a buffer, such as in this use case. Or perhaps you can educate me on how to achieve what I want properly :P

**Comment by jamesb93** [comment]
Oh and patch:

```
<pre><code>
----------begin_max5_patcher----------
859.3ocuWFzaaBCEG+L4SAhKcSJMAaf.am6gcX631koIjIwI0UfMx1zknpsO
6y7Ljlt5jRaI4BH+vIO+y++6mseXhWPgXKUE3+Y+e5648vDOOHTa.ut1dAUj
sKKIJnaAUTkhrgFL09MMcqFhugpyW0HIZlfmWo9vG66AaE7cQwcWii6CxapD
M5RpF9SQcQsgz6po1QTPf+u59TMQu7VFeStjtTa+ZDJdV3TeLFdgBWXaMKb+
OxjEFuOI31X+Yxj1GSGHrKEUUTt1Er9khlUbyjgKNCcyY3wgIYwm.J5fIIDf
I7XvfdCvvo+1L3dFK0R1iDd.DnjWMDwKRaG1QoYvK7oEj2BCGy8ccqWHLJLJ
yEIiqsKMcVxdHyRZaLtttiHTRy3jdJaGB6lS7Q4b5KvZbLXGihfWYoi+Jriv
ZQy50T4e82HDt.M7UB55RAQ2RaAgu4jDmjEBBZJvpcQ4kwBqHU0J+PejCfSF
SCLJFAhZH.2h3KtnZFt0MtJ4fwmMcMJ5.lyhFeYsnQqEbWPsWPqIRREUSk4T
NonjdX0zAJrur+0JtHrs3ab+yyu+cIorzmVzH8uhwM56UtV3lMlF4tpSnTXm
+rrKtQF3z+NAeS4tYD1ZGDu374ns7Z2xEgStbUp.k1bnA5Fyw8nqx62R5DB+
ntCbuG2p6nT73K7GCci5rxujUHEJRNgSJ2oXpY06bfbzXhbJJ4PjiVbt852S
jbSwJ3K44UDFOO+4GczE2H2bGcpCg.l8gX56Vxiyfoi3vWvz2EbMyVrMX9OD
kMFsc92HKMFXg5V+uby7uqnR076J1M+Fwxl1C721gs9Yy+pQoIxcyOghSZzh
VWwgEyUj6MKKLSFlwcNQqkLytC1qY4se124O0KXkoD5lmD4LN5Myw6z2J3lY
5agTD.gAmSu+AlZCJY7++dhf7zF+olJknQtrWb6u0m+iJzJpRy3v8DOnSHae
b5aGbhPCHQOcvHjqnxiWebTybj6LG9tx7PRb6M4NCYFOjT2Ncidm55fXDeNz
0jAjYLdDrtQWnkHWpkhsGz6MjHasFRc88lZZccFxgYqp6DfflMEZx31lKflR
58r99C0MCHRyVGZS82Fos341E1yfDTILVCdCqycXnyjRXav1M7T0DKHvtkS9
yj+AG83fSB
-----------end_max5_patcher-----------
</code></pre>
```

**Comment by shakfu** [comment]
I did a test of pyloudnorm on just python:

```python

In [1]: import soundfile as sf

In [2]: import pyloudnorm as pyln

In [3]: data, rate = sf.read("example.wav")

In [4]: len(data)
Out[4]: 294000

In [5]: loudness = meter.integrated_loudness(data)

In [6]: loudness
Out[6]: -12.147545188345584

In [7]: normed = pyln.normalize.loudness(data, loudness, -12.0)

In [8]: len(normed)
Out[8]: 294000

In [9]: outsize = (normed.shape[0] / rate) * 1000

In [10]: outsize
Out[10]: 6666.666666666667

In [11]: len(normed)
Out[11]: 294000
```

Since outsize is smaller than the original and normed sample, the error is occurring when you write a file of a given length to a new buffer which is smaller. If the buffer was bigger then there wouldn't be an error should be no error.

Can you try to allocate to the size of normed or just sice the array to fit?

**Comment by jamesb93** [comment]
I think it might not have centered FFT's and therefore discards half a window, or a full window. In any case, it smells like one of those windowing caveats :).

I'll play some more with getting the size right. Autosizing, would be nice as a parameter to the set_samples function, though I see how it starts to become a bit 🪄 magical

**Comment by jamesb93** [comment]
Also, if a buffer~ exists patch-side and you `create_empty_buffer` the buffer reference that is returned is valid, however the size is ignored. This seems to behave more like `get_buffer` then whereas I would expect it to resize.

**Comment by shakfu** [comment]
Are you saying that if `buffer1` exists and `create_empty_buffer` is called with the name of `buffer1` a valid ref is returned but size is ignored? If so, that's weird, it should really raise a non-crashing error.

With respect to resizing, there isn't an obvious api to do so however there are hints that this is possible as per a [2013 post by Joshua Kit Clayton](https://cycling74.com/forums/buffer-access-with-sdk6-1-1-buffer_perform_begin-buffer_locksamples):

> locksamples is safe to parallelize, and there are no issues with poly~. Whether you are reading or writing from/to the sample values, you are only reading the samples pointer, and are considered a "reader".
> It is the things which reallocate the sample memory that modify the memory pointer of samples (not the sample values) which are considered a writer, and those use an exclusive lock (locking out all other readers and writers).
> While it's implemented differently, you can think of it like a pthread_rwlock, where locksamples is a rdlock, and buffer reallocation is a wrlock.  
> We recommend avoiding being a writer, and instead use messages to the buffer object for such reallocation, but if you're really curious about this stuff, look at ext_buffer.h, we describe the lower level calls which you should generally avoid, copied below for your convenience, but left out of the top level SDK html to discourage their use. 
> However the short answer is if you're not reallocating buffer memory, you can just use locksamples/unlocksamples.

```c
// Internal or low-level functions

// buffer_perform functions to replace the direct use of
// atomics and other buffer state flags from the perform method
// wrapped by buffer_locksamples() and buffer_unlocksamples()
t_max_err buffer_perform_begin(t_buffer_obj *buffer_object);
t_max_err buffer_perform_end(t_buffer_obj *buffer_object);

// utility function for getting buffer info in struct form
// without needing to know entire buffer struct
t_max_err buffer_getinfo(t_buffer_obj *buffer_object, t_buffer_info *info);

// the following functions are not to be called in the perform method
// please use the lightweight buffer_perform methods

// use buffer_edit functions to collapse all operations of
// locking heavy b_mutex, setting b_valid flag,
// waiting on lightweight atomic b_inuse, etc.
t_max_err buffer_edit_begin(t_buffer_obj *buffer_object);
t_max_err buffer_edit_end(t_buffer_obj *buffer_object, long valid);  // valid 0=FALSE, positive=TRUE, negative=RESTORE_OLD_VALID (not common)
```

From the above it may be possible to reallocate memory while using the "write lock" of these two methods

```c
t_max_err buffer_perform_begin(t_buffer_obj *buffer_object);
t_max_err buffer_perform_end(t_buffer_obj *buffer_object);
```

Otherwise, there's another way which may be easier which I will reference [this post] Emmanuel Jourdan:

> You can also create a buffer just like this
```
t_atom a;
atom_setsym(&a, gensym("toto"));
t_object *b = object_new_typed(CLASS_BOX, gensym("buffer~"), 1, &a);
atom_setsym(&a, gensym("anton.aif"));
typedmess(b, gensym("replace"), 1, &a);
```

So another is perhaps to do via temporary files since the `replace` message explicitly resizes the buffer.

**Comment by jamesb93** [comment]
I think typically you use `object_method_typed` like so:

```
        t_object* buffer = getBuffer();
        unlockSamps();
        t_atom args[2];
        atom_setlong(&args[1], static_cast<t_atom_long>(channels));
        atom_setlong(&args[0], static_cast<t_atom_long>(frames));
        t_symbol* sampsMsg = gensym("sizeinsamps");
        object_method_typed(buffer, sampsMsg, 2, args, nullptr);
```

Not sure how that reasonably translates to the cpython api or if its possible. I tried doing `api.send(buf, 'samps', 441000)` and it crashed max :)

**Comment by jamesb93** [comment]
You can see an example here in the Fluid Corpus Manipulation code:

https://github.com/flucoma/flucoma-max/blob/a1a00d906a8c37978c44a9b97147df03bf8e6c91/source/include/MaxBufferAdaptor.hpp#L80

**Comment by shakfu** [comment]
Hi @jamesb93 



As a quick update on this issue, I finally found a solution to the buffer resizing problem from c using the current recommend buffer api. I've written briefly about it in a [this](https://cycling74.com/forums/resizing-buffer-notify) post on the Cycling74 forums.

While the flucoma code was very helpful, and it mostly used most aspects of the latest Max buffer c-api, it didn't (crucially for my case) use the part that handled the atomic access to the buffer and instead used an alternate c++ standard lib way to handle this successfully.

For `py`, it's best to stay very close to the Max c-api and finally figured it out after some experimentation.

Now that the c-code is working adequately, the next task is to apply this method to `py` and figure out how to expose in python code running on the external. 

To this end, I would first like to try to do this at the cython level if possible and if it proves too difficult (because of the callbacks), the straightforward fall back is to implement it as a c-method and then just call it from cython. In both cases, the resize method will be exposed to python code.

**Comment by shakfu** [comment]
Scratch that, I spoke too soon there's a critical bug in the c-code which is destroying the buffer after resize..

**Comment by shakfu** [comment]
Hi @jamesb93

Ok, I've added buffer resize support. It's not perfect because I couldn't wrap the resize operation in a `defer_low()` as is recommended and do a pure cython implementation, but it works nonetheless and is usable.

Please see `examples/tests/test_buffer.py` and the `patchers/tests/test_buffer_resize.maxpat`, you can also see `examples/tests/test_buffer_scripting.maxpat` for an illustration why `api.send` won't work with a buffer name but will work with the scripting name of the buffer.

**Comment by shakfu** [comment]
@jamesb93 

Added auto-resizing of `buffer buf.set_samples()` , and also some generic methods to resize by duration secs and millisecs, changing sample rate, etc...

It would be good to get some feedback on the api and to get some external testing.

**Comment by jamesb93** [comment]
Amazing work. Just been distracted with some other work atm, but I will gladly test this out v soon

**Comment by shakfu** [comment]
@jamesb93 

There's been a lot of work on the buffer object and I've even added support for the buffer protocol so it can be accessed by the `Memoryview` object now.. There are a lot of tests to demonstrate this.

It would be nice to get some actual user-level feedback at some point, but in any case, it was a nice set of features that got added as a result of your initial request. I'm going to close this issue now as the implementation is largely done from my side. Feel free to add further comments here if you have any further comments/feedback if you get round to testing it for your applications.

**Comment by jamesb93** [comment]
> @jamesb93
> 
> There's been a lot of work on the buffer object and I've even added support for the buffer protocol so it can be accessed by the `Memoryview` object now.. There are a lot of tests to demonstrate this.
> 
> It would be nice to get some actual user-level feedback at some point, but in any case, it was a nice set of features that got added as a result of your initial request. I'm going to close this issue now as the implementation is largely done from my side. Feel free to add further comments here if you have any further comments/feedback if you get round to testing it for your applications.

This is so generous. Thank you! I want a sabbatical to test it all... Will let you know how I go. I have some plan for demixing / source separation on the horizon.
