### ISSUE TITLE
crash building from source and max 8.6

### ISSUE THREAD

**Issue by jamesb93** [shakfu/py-js#14]
Hi again,

I go on holidays and wanted to do some experimentation with `py-js`. I just compiled from source `017400bf5971fe363b4687ece66c851c91e5651c` and the object crashes as soon as I open the help file. Are you able to repro on your end?

**Comment by shakfu** [comment]
@jamesb93

 Hi James, apologies I missed your issue for some reason. Can you provide some more details with the current version in `main` and also your platform and why did you try to do exactly.

**Comment by shakfu** [comment]
I just cut a new release with the latest python stable 3.12.4 engine so feel free to download one of these depending on your requirements.

Since I haven't heard back from you for several months, I'll close this issue.

**Comment by jamesb93** [comment]
Apologies for not doing my part here and testing after you got back to me, things got busy IRL.

I've just tested the new api additions and numpy support. As always, fantastic...

**Comment by shakfu** [comment]
@jamesb93 Thanks. 

Hope you find the latest release useful!
