### ISSUE TITLE
Max crash while loading or executing Python scripts

### ISSUE THREAD

**Issue by francescopapaleo** [shakfu/py-js#8]
Hi
Thanks for the amazing work. It's really something that is missing for Max users!

I have been playing around with the externals, either from package or compiled, on my 2015 MacBook with 10.15 (used make homebrew-ext). While sending messages to the py object, Max has crashed:

Max(45323,0x1119fbdc0) malloc: *** error for object 0x12695e1d0: pointer being freed was not allocated

The patch is pretty basic, just the minimum to test the possibilities of py-js and python.
Any hint is welcome.

<img width="972" alt="py-js" src="https://user-images.githubusercontent.com/98514696/221510759-1da29fe1-8626-4f54-90b9-35f33694137b.png">

**Comment by shakfu** [comment]
Hi @mainspare 

Thanks for your interest in `py-js`

Sending messages to objects is something that's quite well demonstrated in the included patcher files.

I suggest you looking at `py-js/patchers/py_general.maxpat` for a working example.

Note that before sending messages between named objects (i.e. objects with specified scripting names), you have to send the `[py]` object a `[scan]` message.

This step is necessary since it requests the `[py]`  object to scan the whole patch for objects with names. Without doing this, it will not work. See the examples in this file.

**Comment by shakfu** [comment]
@francescopapaleo 

How did you get along with solution outlined above?

**Comment by francescopapaleo** [comment]
@shakfu 
I had already seen the tutorials, and I don't doubt a second that `py-js` work well.
My Max is crashing also when there's only one `[py]` object in the patch and no other named instances. The only answer that I could find is that my compiling process was warning about a `numpy` conflict, hence my script (that imports `numpy`)   must be the cause of these crashes. I wanted to do more tests with simplified patches and script, but didn't have time. I'll come back to it asap

**Comment by shakfu** [comment]
I think that's the problem. Numpy support is still a work-in-progress so I'd try your script with the numpy import

**Comment by francescopapaleo** [comment]
Yes, absolutely. Thanks a lot for getting back!

**Comment by shakfu** [comment]
I've disabled the auto-enabling of `numpy` in `api.pyx` if it is importable. It is now manually enabled at the `Makefile` level. Previously this worked out-of-the-box in a local install of `py-js` (if` numpy` was available), but required an installation of `numpy` into the external or package in another portable variations, so was not so straightforward for someone who just wanted to use the features of the `cython api` (and not `numpy`).

I've also enabled `python 3.11.x` support for all build variations.

I suggest you try again and play around with `py-js/patchers/py_general.maxpat`

**Comment by shakfu** [comment]
@francescopapaleo 

Any further progress after recent changes?

**Comment by francescopapaleo** [comment]
Hi @shakfu, I haven't had the opportunity to recompile and test. Will do asap.

**Comment by shakfu** [comment]
@francescopapaleo Ok, let me know how it goes when you can. 

I have personally tested your sequence on macOS 13.2.1 (Ventura) on an intel MacBook pro with homebrew python installed (python 3.11.2) as follows:

```bash
git clone https://github.com/shakfu/py-js.git
cd py-js
make homebrew-ext
open patchers/py_general.maxpat
```
Now click on the `[scan]` button in the bottom left of the patcher, and experiment with sending objects using the buttons around it.

**Comment by shakfu** [comment]
@francescopapaleo did you every manage to test this as per the above?
